services:
  db:
    build: ./postgres

  redis:
    build: ./redis

  celery:
    build:
      context: ./celery
      args:
        GID: ${GID}

  web:
    build:
      context: ./web
      args:
        GID: ${GID}

  proxy:
    build: ./proxy

  ollama:
    build: ./ollama