services:
  ollama:
    extends:
      file: docker-compose.yml
      service: ollama
    build:
      context: ./ollama
      dockerfile: ${GPU_TYPE:+${GPU_TYPE}.Dockerfile}
    deploy:
      resources:
        reservations:
          devices:
            - driver: ${DOCKER_RUNTIME}
              count: all
              capabilities: [gpu]
    environment:
      # GPU Settings
      - NVIDIA_VISIBLE_DEVICES=all
      - NVIDIA_DRIVER_CAPABILITIES=all
      - HSA_OVERRIDE_GFX_VERSION=10.3.0
      - ROCR_VISIBLE_DEVICES=all
    group_add:
      - video
      - render
    devices:
      - /dev/kfd:/dev/kfd  # AMD ROCm specific
      - /dev/dri:/dev/dri  # AMD ROCm specific
    profiles:
      - gpu
