name: Release

on:
  push:
    branches:
      - master
    tags:
      - v?[0-9]+.[0-9]+.[0-9]+ # semver

jobs:
  release:
    if: github.event_name == 'push' && startsWith(github.ref, 'refs/tags/')
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Create release
        uses: softprops/action-gh-release@v2
        with:
          generate_release_notes: true
